### ISSUE TITLE
Speed 1.5

### ISSUE THREAD

**Issue by chrisg77** [ispedals/Faster-Video#1]
Thank you for a hugely useful plugin.

My question: most videos with speech are best played at 1.5 speed, something i watch daily. Can this be made an option, instead of having to select +.25 twice?

**Comment by ispedals** [comment]
I like the granularity of being able to choose between 1.25, 1.5, and 1.75. The reason I didn't add 1.5X as an option is because most video players, including the built-in Firefox player and the Youtube player, already give the option for 1.5X.

**Comment by chrisg77** [comment]
Yes your granularity is a great thing. I often watch videos hosted by vimeo, and this is where 1.5x is cumbersome to set up.

**Comment by ispedals** [comment]
I've released a new version of the addon where there are preferences where users can now change the speeds that are displayed. Thanks for your feedback!

**Comment by chrisg77** [comment]
You're awesome.
