### ISSUE TITLE
Replace browser's menuitem with extension's menuitem

### ISSUE THREAD

**Issue by Gitoffthelawn** [ispedals/Faster-Video#3]
Great job!

Can you replace the browser's more limited menuitem with this extension's menuitem?

If not, what about placing the extension's menuitem directly above the browser's menuitem instead of at the bottom of the context menu?

**Comment by ispedals** [comment]
Sadly, Firefox does not make it easy to replace the current browser menu and I have no control about where the extension menu gets placed.

**Comment by Gitoffthelawn** [comment]
OK.  Thanks.

Here's a couple CSS workarounds:

Removing the browser's built-in menu item can be accomplished with:
`#context-media-playbackrate { display: none !important; }`

The context menu menuitems can be reordered using:
` -moz-box-ordinal-group`

Moving it into the right spot could be a little challenge with CSS, but moving a menuitem to the top can be accomplished with:
`[identifier] -moz-box-ordinal-group: 0`

Can you add an identifier to the extension's menuitem?  It will make it easier to code CSS to modify it's position.

**Comment by ispedals** [comment]
I did not know about `-moz-box-ordinal-group`, thanks! I have submitted the addon for review.

**Comment by Gitoffthelawn** [comment]
You're welcome!

`moz-box-ordinal-group` is useful for many things (toolbar button order too!).

Instead of doing `.addon-context-menu-item[label^="Playback Rate"]`, what do you think about adding an identifier instead?

This will:
 1. Be more efficient.
 2. Permit future localization.

**Comment by ispedals** [comment]
The Addon SDK only allows setting the label attribute.

**Comment by Gitoffthelawn** [comment]
Thanks.  Interesting.  Is this a limit for menuitems?  I know for toolbar buttons you can set an identifier and one or more classes.
