### ISSUE TITLE
Menuitem disappears when video is paused

### ISSUE THREAD

**Issue by Gitoffthelawn** [ispedals/Faster-Video#4]
The browser's built-in *playback rate* menuitem persists when a video is paused, but the extension's menuitem disappears.

Can you allow the extension's context menuitem to appear, even when the video (or audio) is paused?

**Comment by ispedals** [comment]
The thing I was guarding by requiring the element be playing was to be able to identify the intended element on a page with many media elements. I know check to see whether the intended element is known, or if there is only 1 element on the page and allow changing the playback rate regardless of play status. The playing criterion still applies if there is more than one media element on the page.

Thanks!

**Comment by Gitoffthelawn** [comment]
Thanks!  Looking forward to it!
