### ISSUE TITLE
Default video speed

### ISSUE THREAD

**Issue by matrixik** [ispedals/Faster-Video#5]
Hello, thank you for creating this addon.

Could you add option to set default speed for all videos? I always increase speed of every video so having default speed would be great.

**Comment by ispedals** [comment]
I'm glad you like the addon. Sadly, setting a default speed would require constantly checking if a video element exists on a web page, which would have too big a performance impact.

**Comment by matrixik** [comment]
Thank you for reply.

Just some random thinking:
Then maybe this option would only be available on main video domains (like youtube.com)
Now I'm using this script for it:
https://greasyfork.org/en/scripts/13807-youtubedefaultspeed
